#!/bin/bash
################################################################################
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, version 3 of the License.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
################################################################################

have_orphans=0

for i in $(pacman -Qmq); do
        status=`cower -i $i | grep Maintainer | awk '{split($0,a,": "); print a[2]}'`
        if [ "$status" == "(orphan)" ]; then
                echo $i
                have_orphans=1
        fi
done

if [ $have_orphans -eq 0 ]; then
        echo "No AUR orphans found!"
fi
